export const environment = {
  production: false,
  version: "1.1.1",
  defaultHostApi: "https://mapi.metashark.tv/",
  // oneSignal: "here_one_signal_key",
  // googleFirebase: "here_google_firebase_key",
  // fileUploadService: "file_upload_service_link",
  page_limit: 15,
  apiUrls: {
    getUserIp: "https://jsonip.com/",
    auth: "https://mapi.metashark.tv/user/auth/login",
    registration: "https://mapi.metashark.tv/user/auth/registration",
    passwordRestore: "https://mapi.metashark.tv/user/auth/password-restore",
    passwordRestoreConfirm:
      "https://mapi.metashark.tv/user/auth/password-restore/confirm",
    emailConfirm: "https://mapi.metashark.tv/user/auth/confirm/email",
    emailCodeResend: "https://mapi.metashark.tv/user/auth/resend/email",
    moviesList: "https://mapi.metashark.tv/movie",
    singleMovie: "https://mapi.metashark.tv/movie/{imdb}",
    singleMovieVideo:
      "https://mapi.metashark.tv/movie/{imdb}/view?ip={ip}&lang=en",
    singleMovieVideoMovapi: "https://movapi99.com/playlist/{imdb}.json",
    profile: "https://mapi.metashark.tv/user/profile",
    passwordChange: "https://mapi.metashark.tv/user/profile/password-change",
    movieSearch: "https://mapi.metashark.tv/movie/search",
    autocomplete: "https://mapi.metashark.tv/movie/autocomplete",
    favourite: "https://mapi.metashark.tv/movie/favorites",
    favouriteRemove: "https://mapi.metashark.tv/movie/{id}/favorites",
    genres: "https://mapi.metashark.tv/movie/genre",
    countries: "https://mapi.metashark.tv/movie/country",
    commentsList: "https://mapi.metashark.tv/movie/{id}/comment/list",
    commentPost: "https://mapi.metashark.tv/movie/{id}/comment",
  },
};
